apiVersion: v1
kind: Service
metadata:
  name: x
  namespace: kube-monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: prometheus-server
  type: NodePort 
  ports:
    - port: 9090
      targetPort: 9090 
      protocol: TCP
      name: grafana