---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-prod-sa
  namespace: prod

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ci-prod-role
  namespace: prod
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ci-prod-rolebinding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: ci-prod-sa
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-prod-role